### ISSUE TITLE
search function throwing console errors

### ISSUE THREAD

**Issue by Cordelya** [lindylearn/aboutideasnow#11]
Someone linked to aboutideasnow.com and after a quick visit to check it out, I dropped the link to some of my friends. Both they and I noticed that the search function just spins forever and doesn't return results. If I pull up the dev console, I get the following relevant error:

```js
Uncaught (in promise) r: Request failed with HTTP code 404 | Server said: Not found.
    at r [as constructor] (https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:1:5205)
    at new r (https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:1:8281)
    at n.customErrorForResponse (https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:6:13949)
    at https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:6:10312
    at c (https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:6:5897)
    at Object.next (https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:6:5201)
    at c (https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:6:5383)
    at Object.next (https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:6:5201)
    at l (https://aboutideasnow.com/_app/immutable/nodes/2.Bk4Z7bN0.js:6:4761)
r @ 2.Bk4Z7bN0.js:1
r @ 2.Bk4Z7bN0.js:1
n.customErrorForResponse @ 2.Bk4Z7bN0.js:6
(anonymous) @ 2.Bk4Z7bN0.js:6
c @ 2.Bk4Z7bN0.js:6
(anonymous) @ 2.Bk4Z7bN0.js:6
c @ 2.Bk4Z7bN0.js:6
(anonymous) @ 2.Bk4Z7bN0.js:6
l @ 2.Bk4Z7bN0.js:6
await in l (async)
g @ 2.Bk4Z7bN0.js:18
l @ 2.Bk4Z7bN0.js:12
```

I get the same issue in both Chromium and Firefox.
I'm using Pop! OS

It also did this in Chrome on Android 14.

**Comment by phgn0** [comment]
Okay I don't know what happened. The cluster returns the 404 error when querying against the `content` or `embedding` fields, which may mean that some entries and/or the collection schema is corrupted.

I created a new index and am currently inserting all posts into it.

**Comment by phgn0** [comment]
Seems like the new index is relatively stable now. Thanks for reporting this @Cordelya!
